{% set name = "pyincore-viz" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
 
source:
  path: ../

  # This should be come from a URL. May be from the build server?
  #url: {{ name }}-{{ version }}.tar.gz
  #md5: {{ hash_value }}
 
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv . " # verbose
  skip: True  # [py<36]
 
requirements:
  build:
    - python>=3.9
    - pip
    - numpy>=1.26.0,<2.0a0
 
  host:
    - python>=3.9
    - pip
    - numpy>=1.26.0,<2.0a0
     
  run:
    - python>=3.9
    - {{ pin_compatible('numpy') }}
    - gdal
    - branca>=0.3.0
    - contextily>=1.0.0
    - deprecated
    - geopandas>=0.14.0
    - ipyleaflet>=0.16.0
    - ipywidgets>=7.6.0
    - lxml>=4.6.3
    - matplotlib>=3.8.0
    - networkx>=3.2.1
    - owslib>=0.17.1
    - pandas>=2.1.2
    - pillow
    - pyincore>=1.11.0
    - rasterio>=1.3.9
 
test:
  # Python imports
  imports:
    - pyincore_viz
   
  requires:
    # Put any additional test requirements here.  For example
    - pytest<8
    - pycodestyle>=2.6.0
    - python-jose>=3.0

  commands:
    # You can put built-in test commands to be run here.  Use this to test that the entry points work.
     python -c "import pyincore_viz; print('SUCCESS')" #; pyincore.test_client()"
    # You can also put a file called run_test.py in the recipe that will be run at test time.
 
about:
  home: https://incore.ncsa.illinois.edu
  license: MPL-2.0
  summary: 'Python library for visualization and utilities of pyIncore'
  description: 'pyincore-viz is a Python project that provides visualization and other utilities for use with 
  pyincore'
  dev_url: https://github.com/IN-CORE/pyincore-viz
  doc_url: https://incore.ncsa.illinois.edu/doc/incore
