{% set name = "pyincore-viz" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
 
source:
  path: ../

  # This should be come from a URL. May be from the build server?
  #url: {{ name }}-{{ version }}.tar.gz
  #md5: {{ hash_value }}
 
build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv . " # verbose
  skip: True  # [py<36]
 
requirements:
  build:
    - python>=3.6
    - pip
    - numpy>=1.16
 
  host:
    - python>=3.6
    - pip
    - numpy>=1.16
     
  run:
    - python>=3.6
    - {{ pin_compatible('numpy') }}
    - branca==0.5.0
    - contextily==1.2.0
    - deprecated==1.2.13
    - geopandas==0.11.0
    - ipyleaflet==0.16.0
    - ipywidgets==7.7.1
    - lxml==4.9.0
    - matplotlib==3.5.2
    - networkx==2.8.4
    - osgeo==0.0.1
    - owslib==0.26.0
    - pandas==1.4.3
    - pillow==9.1.1
    - pyincore==1.4.2rc5
    - rasterio==1.2.10
 
test:
  # Python imports
  imports:
    - ipyleaflet
   
  requires:
    # Put any additional test requirements here.  For example
    - pytest>=3.9
    - pycodestyle==2.8.0
    - python-jose==3.3.0

  commands:
    # You can put built-in test commands to be run here.  Use this to test that the entry points work.
     python -c "import pyincore_viz; print('SUCCESS')" #; pyincore.test_client()"
    # You can also put a file called run_test.py in the recipe that will be run at test time.
 
about:
  home: https://incore.ncsa.illinois.edu
  license: MPL-2.0
  summary: 'Python library for visualization and utilities of pyIncore'
  description: 'pyincore-viz is a Python project that provides visualization and other utilities for use with 
  pyincore'
  dev_url: https://github.com/IN-CORE/pyincore-viz
  doc_url: https://incore.ncsa.illinois.edu/doc/incore
