name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - ipopt>=3.11
  - numpy>=1.16
  - affine==2.3.1
  - appnope==0.1.3
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - asttokens==2.0.5
  - attrs==21.4.0
  - backcall==0.2.0
  - beautifulsoup4==4.11.1
  - bleach==5.0.0
  - branca==0.5.0
  - certifi==2022.6.15
  - cffi==1.15.0
  - charset-normalizer==2.0.12
  - click==8.1.3
  - click-plugins==1.1.1
  - cligj==0.7.2
  - contextily==1.2.0
  - cycler==0.11.0
  - debugpy==1.6.0
  - decorator==5.1.1
  - defusedxml==0.7.1
  - deprecated==1.2.13
  - ecdsa==0.17.0
  - entrypoints==0.4
  - executing==0.8.3
  - fastjsonschema==2.15.3
  - fiona==1.8.21
  - fonttools==4.33.3
  - geographiclib==1.52
  - geopandas==0.11.0
  - geopy==2.2.0
  - idna==3.3
  - iniconfig==1.1.1
  - ipykernel==6.15.0
  - ipyleaflet==0.16.0
  - ipython==8.4.0
  - ipython-genutils==0.2.0
  - ipywidgets==7.7.1
  - jedi==0.18.1
  - jinja2==3.1.2
  - joblib==1.1.0
  - jsonschema==4.6.0
  - jupyter-client==7.3.4
  - jupyter-core==4.10.0
  - jupyterlab-pygments==0.2.2
  - jupyterlab-widgets==1.1.1
  - kiwisolver==1.4.3
  - lxml==4.9.0
  - markupsafe==2.1.1
  - matplotlib==3.5.2
  - matplotlib-inline==0.1.3
  - mercantile==1.2.1
  - mistune==0.8.4
  - munch==2.5.0
  - nbclient==0.6.4
  - nbconvert==6.5.0
  - nbformat==5.4.0
  - nest-asyncio==1.5.5
  - networkx==2.8.4
  - notebook==6.4.12
  - osgeo==0.0.1
  - owslib==0.26.0
  - packaging==21.3
  - pandas==1.4.3
  - pandocfilters==1.5.0
  - parso==0.8.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==9.1.1
  - pluggy==1.0.0
  - ply==3.11
  - prometheus-client==0.14.1
  - prompt-toolkit==3.0.29
  - psutil==5.9.1
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - py==1.11.0
  - pyasn1==0.4.8
  - pycodestyle==2.8.0
  - pycparser==2.21
  - pygments==2.12.0
  - pyincore==1.4.2rc5
  - pyomo==6.4.1
  - pyparsing==3.0.9
  - pyproj==3.2.1
  - pyrsistent==0.18.1
  - pytest==7.1.2
  - python-dateutil==2.8.2
  - python-jose==3.3.0
  - pytz==2022.1
  - pyyaml==6.0
  - pyzmq==23.2.0
  - rasterio==1.2.10
  - requests==2.28.0
  - rsa==4.8
  - rtree==1.0.0
  - scipy==1.8.1
  - send2trash==1.8.0
  - shapely==1.8.2
  - six==1.16.0
  - snuggs==1.4.7
  - soupsieve==2.3.2.post1
  - stack-data==0.3.0
  - terminado==0.15.0
  - tinycss2==1.1.1
  - tomli==2.0.1
  - tornado==6.1
  - traitlets==5.3.0
  - traittypes==0.2.1
  - urllib3==1.26.9
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - widgetsnbextension==3.6.1
  - wntr==0.4.2
  - wrapt==1.14.1
  - xyzservices==2022.6.0
