name: pyincore_viz
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - branca>=0.3.0
  - contextily>=1.0.0
  - deprecated
  - geopandas>=0.6.1
  - ipyleaflet>=0.16.0
  - ipywidgets>=7.6.0
  - lxml>=4.6.3
  - matplotlib>=2.1.0
  - networkx>=2.2
  - numpy>=1.16.1
  - owslib>=0.17.1
  - pandas>=0.24.1
  - pillow
  - pycodestyle>=2.6.0
  - pyincore>=1.7.0
  - pytest>=3.9.0
  - python-jose>=3.0
  - rasterio>=1.3.3
