name: pyincore_viz
channels:
  - conda-forge
  - defaults
  - in-core
dependencies:
  - gdal
  - branca>=0.3.0
  - contextily>=1.0.0
  - deprecated
  - geopandas>=0.14.0
  - ipyleaflet>=0.16.0
  - ipywidgets>=7.6.0
  - lxml>=4.6.3
  - matplotlib>=3.8.0
  - networkx>=3.2.1
  - numpy>=1.26.0,<2.0a0
  - owslib>=0.17.1
  - pandas>=2.1.2
  - pillow
  - pycodestyle>=2.6.0
  - pyincore>=1.11.0
  - pytest<7.4.4
#  - python-jose>=3.0
#  - rasterio>=1.3.9
#  - azure-core-cpp<=1.10.3
#  - branca<=0.7.0
#  - c-ares<=1.25.0
#  - cryptography<=42.0.0
#  - geopandas<=0.14.2
#  - geopandas-base<=0.14.2
  - openssl<=3.2.0
#  - pixman<=0.43.0
#  - pytest<=7.4.4
#  - pytz<=2023.3.post1
#  - tiledb<=2.19.0
#  - urllib3<=2.1.0
    #zstd 	1.5.5 	None
